Parameters:
  CodeCommitRepoName:
    Type: String
  ECRRepoName:
    Type: String
  ServiceName:
    Type: String
  ImageTag:
    Type: String
    Default: 'latest'
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  CodeBuildServiceRoleArn:
    Type: String
  CodeBuildImage:
    Type: String
  CodePipelineServiceRoleArn:
    Type: String

Resources:
  # ECR repository
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepoName

  # CodeBuild project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join ['', [!Ref ServiceName, '-build']]
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      Source:
        Type: CODECOMMIT
        Location: !Join ['', ['https://git-codecommit.', !Ref 'AWS::Region', '.amazonaws.com/v1/repos/', !Ref CodeCommitRepoName]]
      Artifacts:
        Type: NO_ARTIFACTS
      EnvironmentVariables:
        - Name: IMAGE_TAG
          Value: !Ref ImageTag
        - Name: ECR_REPO_URI
          Value: !Join ['', [!Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref ECRRepoName]]
      TimeoutInMinutes: 5
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Join ['', ['/aws/codebuild/', !Ref ServiceName, '-build']]
          StreamName: !Join ['', ['/aws/codebuild/', !Ref ServiceName, '-build-', !Ref 'AWS::CodeBuild::BuildId']]

  # CodePipeline
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join ['', [!Ref ServiceName, '-pipeline']]
      RoleArn: !Ref CodePipelineServiceRoleArn
      ArtifactStore:
        Location: !Join ['', ['s3://', !Ref 'AWS::AccountId', '-codepipeline-us-east-1']]
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
              OutputArtifacts:
                - Name
